// <auto-generated />
namespace diyetisyenWebUygulamasi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class duzenleme3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(duzenleme3));
        
        string IMigrationMetadata.Id
        {
            get { return "202408151407534_duzenleme3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
